"""Initial migration

Revision ID: 475692aaf55d
Revises: 
Create Date: 2024-08-06 16:29:45.131650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '475692aaf55d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.create_table(
        'account',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('description', sa.Unicode(200)),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # Example of adding a new column, index, or table
    # op.add_column('clients', sa.Column('new_column', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    # Example of reversing the upgrade operation
    # op.drop_column('clients', 'new_column')
    # ### end Alembic commands ###
    op.drop_table('account')
